### ISSUE TITLE
type is undefined

### ISSUE THREAD

**Issue by orizzz** [tsepeti/react-native-counters#4]
hey just want to know your code is really helping me.

here my code 

![image](https://user-images.githubusercontent.com/41751653/80813251-e4ca5300-8bf3-11ea-88f2-11d7846dd2da.png)

and its become like this in console.log

![image](https://user-images.githubusercontent.com/41751653/80813137-a03eb780-8bf3-11ea-9615-a940cb873c7a.png)

all the fuction is going really well and i just dont know why the type come undefined maybe you can help

**Comment by yasaricli** [comment]
I fixed it in version v1.0.1 Thanks @orizzz

**Comment by orizzz** [comment]
thanks for the follow up, i already try it and its still coming undefined

i already try to reinstall it using npm or try specify the version to v1.0.1 but the result still same

its there any thing that i go wrong ?

![image](https://user-images.githubusercontent.com/41751653/80859015-c31aab80-8c87-11ea-9eb3-b63bf0fc273e.png)

this is my packge.json after try to reisntall it using npm
![image](https://user-images.githubusercontent.com/41751653/80859080-2573ac00-8c88-11ea-84e9-bcd71b234cab.png)

this my code
![image](https://user-images.githubusercontent.com/41751653/80859093-3c1a0300-8c88-11ea-8a1a-6c1ed6842247.png)
