### ISSUE TITLE
Type still undefined

### ISSUE THREAD

**Issue by orizzz** [tsepeti/react-native-counters#9]
thanks @yasaricli for the follow up, i already try it and its still coming undefined

i already try to reinstall it using npm or try specify the version to v1.0.1 but the result still same

its there any thing that i go wrong ?

![image](https://user-images.githubusercontent.com/41751653/80859015-c31aab80-8c87-11ea-9eb3-b63bf0fc273e.png)

this is my packge.json after try to reisntall it using npm
![image](https://user-images.githubusercontent.com/41751653/80859080-2573ac00-8c88-11ea-84e9-bcd71b234cab.png)

this my code
![image](https://user-images.githubusercontent.com/41751653/80859093-3c1a0300-8c88-11ea-8a1a-6c1ed6842247.png)

**Comment by yasaricli** [comment]
hi @orizzz 

Current version **1.2.0**, this error has been `resolved`.

Please try deleting `npm cache`.

and install it again.

or create a **type-still-undefined-9** repo and share it with me.

**Comment by orizzz** [comment]
hi @yasaricli it's still not working dont know why
![image](https://user-images.githubusercontent.com/41751653/80915900-65698a80-8d7f-11ea-86c1-970ec4f1a55f.png)

maybe you can look at my project at https://github.com/orizzz/KashierApp
